FROM toposoid/scala-base:2.12.12

WORKDIR /app
ARG TARGET_BRANCH
ENV DEPLOYMENT=local

RUN apt-get update \
&& apt-get -y install git \
&& git clone https://github.com/toposoid/toposoid-knowledgebase-model.git \
&& cd toposoid-knowledgebase-model \
&& git fetch origin ${TARGET_BRANCH} \
&& git checkout ${TARGET_BRANCH}



