name: Header Check
on:
  push:
    branches:
      - feature
  workflow_dispatch:
env:
  PJ_ACTOR: toposoid
  PJ_REPO: toposoid-knowledgebase-model
  PJ_BRANCH: feature
  PJ_VERSION: 0.5-SNAPSHOT
jobs:
  header-check_toposoid-knowledgebase-model:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone ${{ env.PJ_REPO }}
        uses: actions/checkout@v3
        with:
            repository: ${{ env.PJ_ACTOR }}/${{ env.PJ_REPO }}
      - name: Execute tests
        run: |
            cd ${GITHUB_WORKSPACE} && cd ../
            cd ./${{ env.PJ_REPO }}
            docker build --build-arg TARGET_BRANCH=${{ env.PJ_BRANCH }} --tag ${{ env.PJ_REPO }}:${{ env.PJ_VERSION }} -f Dockerfile-workflow .
            docker-compose -f docker-compose-workflow.yml up -d
            docker-compose -f docker-compose-workflow.yml exec -T ${{ env.PJ_REPO }} bash -c "cd ${{ env.PJ_REPO }} && sbt headerCheck"
      - name: Clone toposoid-scala-lib
        uses: actions/checkout@v3
        with:
          repository: ${{ env.PJ_ACTOR }}/toposoid-scala-lib
          ref: ${{ env.PJ_BRANCH }}
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v3
        with:
          images: toposoid/toposoid-scala-lib:${{ env.PJ_VERSION }}
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build And Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: toposoid/toposoid-scala-lib:${{ env.PJ_VERSION }}
          build-args: |
            TARGET_BRANCH=${{ env.PJ_BRANCH }}

